import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SidebarDesktop } from '@/components/sidebar-desktop';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <SidebarDesktop />
        {children}
        {/* <main className='flex flex-col flex-1 bg-muted/50'>{children}</main> */}
      </body>
    </html>
  );
}
